# Fuel Efficiency Prediction

Notebook 01: Data Loading and Understanding

 Goal:
- Load dataset
- Understand features
- Identify target variable
- Check data quality

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [23]:
# df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv')
df = pd.read_csv('../data/mpg.csv')

In [24]:
print("First 5 rows")
print(df.head())

First 5 rows
    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [25]:
print("\nShape")
print(df.shape)

Shape
(398, 9)

In [26]:
print("\nColumns")
print(df.columns)

Columns
Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [27]:
print("\nInfo")
print(df.info())

Info
<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB
None

In [28]:
print("\nStatistics")
print(df.describe())

Statistics
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000
mean    23.514573    5.454774    193.425879  104.469388  2970.424623
std      7.815984    1.701004    104.269838   38.491160   846.841774
min      9.000000    3.000000     68.000000   46.000000  1613.000000
25%     17.500000    4.000000    104.250000   75.000000  2223.750000
50%     23.000000    4.000000    148.500000   93.500000  2803.500000
75%     29.000000    8.000000    262.000000  126.000000  3608.000000
max     46.600000    8.000000    455.000000  230.000000  5140.000000

       acceleration  model_year
count    398.000000  398.000000
mean      15.568090   76.010050
std        2.757689    3.697627
min        8.000000   70.000000
25%       13.825000   73.000000
50%       15.500000   76.000000
75%       17.175000   79.000000
max       24.800000   82.000000

In [29]:
print("\nMissing value")
df.isnull().sum()

Missing value

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [30]:
print("\nTarget Variable")
target = "mpg"

print("Target Variable:", target)

Target Variable
Target Variable: mpg

In [31]:
print("\nFeature Columns")
features = df.columns.drop("mpg")

features

Feature Columns

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model_year', 'origin', 'name'],
      dtype='str')

In [33]:
print("\nAverage MPG")

df["mpg"].mean()

Average MPG

np.float64(23.514572864321607)

In [35]:
print("\nHighest MPG Car")

df.sort_values("mpg", ascending=False).head()

Highest MPG Car

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)

In [36]:
print("\nLowest MPG Car")

df.sort_values("mpg").head()

Lowest MPG Car

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200

In [37]:
print("\nUnique Origins")

df["origin"].unique()

Unique Origins

<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

In [38]:
print("\nNumber of Cars From Each Origin")

df["origin"].value_counts()

Number of Cars From Each Origin

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [39]:
print("\nCheck Missing Horsepower Rows")

df[df["horsepower"].isnull()]

Check Missing Horsepower Rows

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl